enabled: true
allowedOrigins:
  - https://signin.lightapi.net
  - https://lightapi.net
  - https://dev.lightapi.net
  - http://localhost:3000
  - http://networknt.github.io
allowedMethods:
  - GET
  - POST
  - PUT
