version: '2'

services:

  light-router:
    image:  networknt/light-router:latest
    network_mode: host
    ports:
    - 8443:8443
    extra_hosts:
    - "dev.lightapi.net:192.168.1.144"
    - "devsignin.lightapi.net:192.168.1.144"
    volumes:
    - ./config:/config
    - ./lightapi/build:/lightapi/build
    - ./signin/build:/signin/build
