version: '2'

services:

  light-router:
    image:  networknt/light-router:latest
    networks:
    - localnet
    ports:
    - 8443:8443
    extra_hosts:
    - "lightapi.net:192.168.1.144"
    - "signin.lightapi.net:192.168.1.144"
    volumes:
    - ./config:/config
    - ./faucet/build:/faucet/build
    - ./webclient/build:/webclient/build
    - ./lightapi/build:/lightapi/build
    - ./taiji/build:/taiji/build
    - ./signin/build:/signin/build
#
# Networks
#
networks:
    localnet:
        # driver: bridge
        external: true
