# Cors Http Handler Configuration. This is to support connection
# from light-portal single page application which might served
# from another domain/host. You may need to update allowedOrigins.
---
enabled: false
allowedOrigins:
- https://localhost:3000
allowedMethods:
- GET
- POST
- PUT
- DELETE
