version: '2'

services:

  light-router:
    image:  networknt/light-router:latest
    network_mode: host
    ports:
    - 8443:8443
    volumes:
    - ./config:/config
    - ./lightapi/build:/lightapi/build
    - ./signin/build:/signin/build
